kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testa
  namespace: a-test
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
