apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: maven-webapp-build
spec:
  source:
    type: Dockerfile
    dockerfile: >-
      FROM tomcat
      RUN wget https://github.com/Chathuru/maven-web-project/releases/download/v1.0/maven-webapp.war -O /usr/local/tomcat/webapps/maven-webapp.war
      
      CMD ["catalina.sh", "run"]
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'maven-webapp:latest'
