apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/description: >-
      Checks if all namespaces have either set prod=true, staging =true or dev=true
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/title: Test Namespace Annotation
  name: test-namespace-annotation
spec:
  background: true
  rules:
    - exclude:
        any:
          - resources:
              namespaces:
                - openshift*
                - kube*
                - default
      match:
        any:
          - resources:
              kinds:
                - Namespace
      name: test-namespace-annotation
      validate:
        anyPattern:
          - metadata:
              annotations:
                openshift.io/node-selector: dev=true
          - metadata:
              annotations:
                openshift.io/node-selector: staging=true
          - metadata:
              annotations:
                openshift.io/node-selector: prod=true
          - metadata:
              labels:
                any-environment: "true"
        message: All new Namespaces must have an annotaiton for the nodeselector (dev, staging, prod).
  validationFailureAction: audit

